/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
// FloorLevel : Floor level
type FloorLevel string

// List of FloorLevel
const (
	FLOOR_LEVEL_BASEMENT FloorLevel = "basement"
	FLOOR_LEVEL_GROUND FloorLevel = "ground"
	FLOOR_LEVEL_MIDDLE FloorLevel = "middle"
	FLOOR_LEVEL_TOP FloorLevel = "top"
	FLOOR_LEVEL_FLOOR_1 FloorLevel = "floor_1"
	FLOOR_LEVEL_FLOOR_2 FloorLevel = "floor_2"
	FLOOR_LEVEL_FLOOR_3 FloorLevel = "floor_3"
	FLOOR_LEVEL_FLOOR_4 FloorLevel = "floor_4"
	FLOOR_LEVEL_FLOOR_5 FloorLevel = "floor_5"
	FLOOR_LEVEL_FLOOR_6 FloorLevel = "floor_6"
	FLOOR_LEVEL_FLOOR_7 FloorLevel = "floor_7"
	FLOOR_LEVEL_FLOOR_8 FloorLevel = "floor_8"
	FLOOR_LEVEL_FLOOR_9 FloorLevel = "floor_9"
	FLOOR_LEVEL_FLOOR_10 FloorLevel = "floor_10"
	FLOOR_LEVEL_FLOOR_11 FloorLevel = "floor_11"
	FLOOR_LEVEL_FLOOR_12 FloorLevel = "floor_12"
	FLOOR_LEVEL_FLOOR_13 FloorLevel = "floor_13"
	FLOOR_LEVEL_FLOOR_14 FloorLevel = "floor_14"
	FLOOR_LEVEL_FLOOR_15 FloorLevel = "floor_15"
	FLOOR_LEVEL_FLOOR_16 FloorLevel = "floor_16"
	FLOOR_LEVEL_FLOOR_17 FloorLevel = "floor_17"
	FLOOR_LEVEL_FLOOR_18 FloorLevel = "floor_18"
	FLOOR_LEVEL_FLOOR_19 FloorLevel = "floor_19"
	FLOOR_LEVEL_FLOOR_20 FloorLevel = "floor_20"
	FLOOR_LEVEL_FLOOR_21_OR_ABOVE FloorLevel = "floor_21_or_above"
)