/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type RoofInsulation string

// List of RoofInsulation
const (
	ROOF_INSULATION_NO RoofInsulation = "no"
	ROOF_INSULATION_PARTIAL RoofInsulation = "partial"
	ROOF_INSULATION_INSULATED RoofInsulation = "insulated"
	ROOF_INSULATION_ADDITIONAL RoofInsulation = "additional"
	ROOF_INSULATION_DWELLING RoofInsulation = "dwelling"
)