/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm

type ValuationPriceDistribution struct {
	// left subrange boundary
	PriceFrom int32 `json:"priceFrom,omitempty"`
	// right subrange boundary
	PriceTo int32 `json:"priceTo,omitempty"`
	// Probability that price is within the specified boundaries
	Probability float64 `json:"probability,omitempty"`
}
