/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm

type Valuation struct {
	// Predicted price, pound
	MostProbablePrice int32 `json:"mostProbablePrice,omitempty"`
	// Lower price boundary, pound
	PriceRangeFrom int32 `json:"priceRangeFrom,omitempty"`
	// Higher price boundary, pound
	PriceRangeTo int32 `json:"priceRangeTo,omitempty"`
	// Probability (in percents) that actual price is within the specified boundaries
	Confidence int32 `json:"confidence,omitempty"`
	// Describes the probabilities (in percents) that actual price is within particular subranges
	PriceDistribution []ValuationPriceDistribution `json:"priceDistribution,omitempty"`
}
