/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm

type AdditionalFeatures struct {
	PriceOfPreviousSale          int32               `json:"priceOfPreviousSale,omitempty"`
	DateOfPreviousSale           string              `json:"dateOfPreviousSale,omitempty"`
	LeaseholdOrFreehold          LeaseholdOrFreehold `json:"leaseholdOrFreehold,omitempty"`
	WallType                     WallType            `json:"wallType,omitempty"`
	WallInsulation               WallInsulation      `json:"wallInsulation,omitempty"`
	WallEnergyEfficiency         EnergyEfficiency    `json:"wallEnergyEfficiency,omitempty"`
	RoofType                     RoofType            `json:"roofType,omitempty"`
	RoofInsulation               RoofInsulation      `json:"roofInsulation,omitempty"`
	RoofEnergyEfficiency         EnergyEfficiency    `json:"roofEnergyEfficiency,omitempty"`
	WindowGlazingType            WindowGlazingType   `json:"windowGlazingType,omitempty"`
	WindowEnergyEfficiency       EnergyEfficiency    `json:"windowEnergyEfficiency,omitempty"`
	CurrentEnergyRating          EnergyRating        `json:"currentEnergyRating,omitempty"`
	PotentialEnergyRating        EnergyRating        `json:"potentialEnergyRating,omitempty"`
	AnnualHeatingCostInPounds    int32               `json:"annualHeatingCostInPounds,omitempty"`
	AnnualHotWaterCostInPounds   int32               `json:"annualHotWaterCostInPounds,omitempty"`
	AnnualLightingCostInPounds   int32               `json:"annualLightingCostInPounds,omitempty"`
	AnnualEnergyConsumptionInKWh int32               `json:"annualEnergyConsumptionInKWh,omitempty"`
	FloorHeightInFoot            float32             `json:"floorHeightInFoot,omitempty"`
	BuiltForm                    BuiltForm           `json:"builtForm,omitempty"`
}
