/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type RoofType string

// List of RoofType
const (
	ROOF_TYPE_PITCHED RoofType = "pitched"
	ROOF_TYPE_FLAT RoofType = "flat"
	ROOF_TYPE_THATCHED RoofType = "thatched"
	ROOF_TYPE_DWELLING RoofType = "dwelling"
)