/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type NewOrResale string

// List of NewOrResale
const (
	NEW_OR_RESALE_NEW NewOrResale = "new"
	NEW_OR_RESALE_RESALE NewOrResale = "resale"
)