/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type WallInsulation string

// List of WallInsulation
const (
	WALL_INSULATION_NO WallInsulation = "no"
	WALL_INSULATION_PARTIAL WallInsulation = "partial"
	WALL_INSULATION_INSULATED WallInsulation = "insulated"
	WALL_INSULATION_ADDITIONAL WallInsulation = "additional"
)