/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm

type PropertyFeatures struct {
	RequiredFeatures RequiredFeatures `json:"requiredFeatures"`
	AdditionalFeatures AdditionalFeatures `json:"additionalFeatures,omitempty"`
}
