/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm

type WindowGlazingType string

// List of WindowGlazingType
const (
	WINDOW_GLAZING_TYPE_SINGLE      WindowGlazingType = "single"
	WINDOW_GLAZING_TYPE_SECONDARY   WindowGlazingType = "secondary"
	WINDOW_GLAZING_TYPE_DOUBLE      WindowGlazingType = "double"
	WINDOW_GLAZING_TYPE_TRIPLE      WindowGlazingType = "triple"
	WINDOW_GLAZING_TYPE_MULTIPLE    WindowGlazingType = "multiple"
	WINDOW_GLAZING_TYPE_PERFORMANCE WindowGlazingType = "high_performance"
)
