/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type EnergyRating string

// List of EnergyRating
const (
	ENERGY_RATING_A EnergyRating = "A"
	ENERGY_RATING_B EnergyRating = "B"
	ENERGY_RATING_C EnergyRating = "C"
	ENERGY_RATING_D EnergyRating = "D"
	ENERGY_RATING_E EnergyRating = "E"
	ENERGY_RATING_F EnergyRating = "F"
	ENERGY_RATING_G EnergyRating = "G"
	ENERGY_RATING_I EnergyRating = "I"
)