/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type LeaseholdOrFreehold string

// List of LeaseholdOrFreehold
const (
	LEASEHOLD_OR_FREEHOLD_FREEHOLD LeaseholdOrFreehold = "freehold"
	LEASEHOLD_OR_FREEHOLD_LEASEHOLD LeaseholdOrFreehold = "leasehold"
)