/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
// PropertyType : type of property
type PropertyType string

// List of PropertyType
const (
	PROPERTY_TYPE_FLAT PropertyType = "flat"
	PROPERTY_TYPE_SEMI_DETACHED_HOUSE PropertyType = "semi_detached_house"
	PROPERTY_TYPE_DETACHED_HOUSE PropertyType = "detached_house"
	PROPERTY_TYPE_TERRACED_HOUSE PropertyType = "terraced_house"
)