/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type EnergyEfficiency string

// List of EnergyEfficiency
const (
	ENERGY_EFFICIENCY_AVERAGE EnergyEfficiency = "average"
	ENERGY_EFFICIENCY_GOOD EnergyEfficiency = "good"
	ENERGY_EFFICIENCY_POOR EnergyEfficiency = "poor"
	ENERGY_EFFICIENCY_VERY_GOOD EnergyEfficiency = "very_good"
	ENERGY_EFFICIENCY_VERY_POOR EnergyEfficiency = "very_poor"
)