/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type BuiltForm string

// List of BuiltForm
const (
	BUILT_FORM_DETACHED BuiltForm = "detached"
	BUILT_FORM_SEMI_DETACHED BuiltForm = "semi_detached"
	BUILT_FORM_ENCLOSED_MID_TERRACE BuiltForm = "enclosed_mid_terrace"
	BUILT_FORM_ENCLOSED_END_TERRACE BuiltForm = "enclosed_end_terrace"
	BUILT_FORM_END_TERRACE BuiltForm = "end_terrace"
	BUILT_FORM_MID_TERRACE BuiltForm = "mid_terrace"
)