/*
 * AVM
 *
 * This is api for AVM (automated valuation machine)
 *
 * API version: 1.0.0
 * Contact: info@enbisys.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avm
type WallType string

// List of WallType
const (
	WALL_TYPE_CAVITY_WALL WallType = "cavity_wall"
	WALL_TYPE_COB WallType = "cob"
	WALL_TYPE_GRANITE_OR_WHIN WallType = "granite_or_whin"
	WALL_TYPE_PARK_HOME_WALL WallType = "park_home_wall"
	WALL_TYPE_SANDSTONE WallType = "sandstone"
	WALL_TYPE_SOLID_BRICK WallType = "solid_brick"
	WALL_TYPE_SYSTEM_BUILD WallType = "system_build"
	WALL_TYPE_TIMBER_FRAME WallType = "timber_frame"
)